---
title: "p8105_hw6_pl2811"
author: "Pei Hsin Lin"
date: "11/30/2021"
output: html_document
---
```{r}
library(tidyverse)
library(dplyr)
library(ggridges)
library(ggplot2)
library(forcats)
library(p8105.datasets)
library(httr)
library(jsonlite)
library(patchwork)
library(knitr)    
library(png)
library(corrplot)
library(ggcorrplot)
```

#### Read and clean the data
```{r}
birthweight <- read.csv(file ="/Users/lin/Desktop/birthweight.csv")
```

```{r}
birthweight = 
birthweight %>% 
  janitor::clean_names() %>%
  drop_na()

#check the variabls's level
str(birthweight)

#change some variabls into factor

birthweight_factor<-birthweight %>%
    mutate_at(vars(babysex, frace, malform, mrace),
                list(factor))

str(birthweight_factor)             

Propose a regression model for birthweight. This model may be based on a hypothesized structure for the factors that underly birthweight, on a data-driven model-building process, or a combination of the two. Describe your modeling process and show a plot of model residuals against fitted values – use add_predictions and add_residuals in making this plot.
```

```{r}
#look up correlation between variables 

model.matrix(~0+., data=birthweight_factor) %>% 
  cor(use="pairwise.complete.obs") %>% 
  ggcorrplot(show.diag = F, type="lower", lab=TRUE, lab_size=2)

There are high correlation in mother’s pre-pregnancy BMI (pppbmi) and mother’s pre-pregnancy weight (ppwt),  mother’s weight at delivery(delwt) and mother’s pre-pregnancy weight(ppwt), mother’s weight at delivery (delwt) and mother’s pre-pregnancy BMI (ppbmi), race of father and mother, baby’s length at birth (blength) and baby’s birth weight (bwt).
#choose varibals by the correlation plot ＃found out pnumlbw and pnumgsa are all 0, drop theme.



fit = lm(bwt ~ babysex + fincome+ frace+ gaweeks +malform+momage+mrace+
           parity+ppbmi+smoken, data = birthweight_factor)
linear.step = step(fit,direction="both")

#choose the model with lowest AIC
fit = lm(bwt ~ babysex + fincome + gaweeks + mrace + parity + ppbmi + 
    smoken, data = birthweight_factor)
linear.step = step(fit,direction="both")

fit %>% 
  broom::tidy() %>% 
  select(term, estimate, p.value) %>% 
  knitr::kable(digits = 3)

modelr::add_residuals( birthweight_factor, fit)
modelr::add_predictions(birthweight_factor, fit)
                        
birthweight_factor %>% 
  modelr::add_residuals(fit) %>% 
  ggplot(aes(x=babysex, fincome,gaweeks,mrace,parity,ppbmi, smoken, y = resid)) + geom_violin()                        
```

